name: continuous-master

on: 
    push:
        branches: 
          - master

jobs:
  build-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update package list
      run: sudo apt-get update -y
    - name: Install markdown
      run: sudo apt-get install -y markdown
    - name: Process rule file
      run: markdown README.md
