name: private-para

on: 
    pull_request:
        branches-ignore: 
          - master
    push:
        branches-ignore: 
          - master

jobs:
  build-parameterized:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update package list
      run: sudo apt-get update -y
    - name: Install markdown
      run: sudo apt-get install -y markdown
    - name: Process rule file
      run: markdown README.md
